import Watch1 from '@/images/test-card-component/watch1.png';
import Watch2 from '@/images/test-card-component/watch2.png';
import Watch3 from '@/images/test-card-component/watch3.png';

export const CARD_INFORMATION = [
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch1,
    price: 15.555,
    product_id: '1',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 7',
    photo_url: Watch2,
    price: 15.555,
    product_id: '2',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'Germany',
    model: 'Molumenzeit S 7',
    photo_url: Watch3,
    price: 15.555,
    product_id: '3',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch1,
    price: 15.555,
    product_id: '4',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch2,
    price: 15.555,
    product_id: '5',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 7',
    photo_url: Watch3,
    price: 15.555,
    product_id: '6',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch1,
    price: 15.555,
    product_id: '7',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch2,
    price: 15.555,
    product_id: '8',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 7',
    photo_url: Watch3,
    price: 15.555,
    product_id: '9',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch2,
    price: 15.555,
    product_id: '10',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch3,
    price: 15.555,
    product_id: '11',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch1,
    price: 15.555,
    product_id: '12',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch2,
    price: 15.555,
    product_id: '13',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch3,
    price: 15.555,
    product_id: '14',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch1,
    price: 15.555,
    product_id: '15',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch2,
    price: 15.555,
    product_id: '16',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch3,
    price: 15.555,
    product_id: '17',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 8',
    photo_url: Watch1,
    price: 15.555,
    product_id: '18',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 9',
    photo_url: Watch3,
    price: 15.555,
    product_id: '19',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'USA',
    model: 'Molumenzeit S 9',
    photo_url: Watch1,
    price: 13.555,
    product_id: '20',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'GERMANY',
    model: 'Molumenzeit S 9',
    photo_url: Watch2,
    price: 12.555,
    product_id: '21',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'GERMANY',
    model: 'Molumenzeit S 9',
    photo_url: Watch3,
    price: 11.555,
    product_id: '22',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'GERMANY',
    model: 'Molumenzeit S 9',
    photo_url: Watch1,
    price: 15.222,
    product_id: '23',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'GERMANY',
    model: 'Molumenzeit S 9',
    photo_url: Watch2,
    price: 15.33,
    product_id: '24',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 9',
    photo_url: Watch3,
    price: 15.2,
    product_id: '25',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 9',
    photo_url: Watch1,
    price: 15.1,
    product_id: '26',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 9',
    photo_url: Watch2,
    price: 11.555,
    product_id: '27',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
  {
    case_color: 'black',
    country: 'UKRAINE',
    model: 'Molumenzeit S 10',
    photo_url: Watch2,
    price: 10.555,
    product_id: '27',
    strap_color: 'white',
    type: 'Watch',
    case: '316L Stainless-steel',
    case_size: 42,
    dial_color: 'Black Metallic',
    coating: 'Color anodized anti-scratch',
    glass: 'Sapphire Crystal',
    instantaneus_rate: '-10/ +20 sec/month',
    movement: 'Movement: Swiss Parts RONDA 762E',
    standard_battery_life: '10 years',
    straps: 'Quick release',
    water_resistance: '5 ATM/50 meters',
  },
];
